Vectors

In [1]:
import numpy as np
from vectors import Point, Vector
import functools

v1 = Vector(1, 2, 3)
v2 = Vector(10, 20, 30)

In [2]:
print(v1.add(10))

Vector(11.0, 12.0, 13.0)


In [3]:
print(v1.sum(v2))

Vector(11.0, 22.0, 33.0)


In [4]:
print(v1.multiply(4))

Vector(4.0, 8.0, 12.0)


In [5]:
v1.cross(v2)

Vector(0, 0, 0)

Matrices

In [6]:
import numpy as np
A = np.matrix(
 [[3, 2],
 [4, 6]])
B = np.matrix(
 [[1, 4],
 [2, 0]])

In [7]:
C = A + B
print(C)

[[4 6]
 [6 6]]


In [8]:
import numpy as np
A = np.matrix(
    [[1, 4],
     [2, 9]])

B = np.matrix(
    [[7, -9],
     [4, 6]])

C = A - B
print(C)

[[-6 13]
 [-2  3]]


In [9]:
import numpy as np
A = np.matrix(
    [[1, 4],
     [2, 0]])

B = np.matrix(
    [[3, 2],
     [4, 6]])

In [10]:
C = A * B
print(C)

[[19 26]
 [ 6  4]]


In [11]:
B = A + 8
print(B)

[[ 9 12]
 [10  8]]


In [12]:
A = np.matrix(
 [[3, 2],
 [4, 6]])
deter = np.linalg.det(A)
print(deter)

10.000000000000002


In [13]:
import numpy as np
matrix = np.matrix(
    [[3, 6, 7],
     [2, 7, 9],
     [5, 8, 6]])

transpose = np.transpose(matrix)
print(transpose)

[[3 2 5]
 [6 7 8]
 [7 9 6]]


In [14]:
matrix = np.matrix(
    [[3, 6, 7],
     [2, 7, 9],
     [5, 8, 6]])

inverse = np.linalg.inv(matrix)
print(inverse)

[[ 1.2  -0.8  -0.2 ]
 [-1.32  0.68  0.52]
 [ 0.76 -0.24 -0.36]]


Solving simultaneous linear equations

In [15]:
A = np.matrix(
 [[1, 4],
 [2, 0]])

B = np.matrix(
 [[3, 2],
 [4, 6]])

In [16]:
X = np.linalg.solve(A, B)
print(X)

[[ 2.    3.  ]
 [ 0.25 -0.25]]


Eigenvalues and eigenvectors

In [17]:
matrix = np.matrix(
    [[3, 6, 7],
     [2, 7, 9],
     [5, 8, 6]])

eigvals = np.linalg.eig(matrix)
print(eigvals)

(array([18.03062661,  0.53948277, -2.57010939]), matrix([[-0.52213277, -0.69701957, -0.23035157],
        [-0.59400273,  0.64684805, -0.6406727 ],
        [-0.6119952 , -0.3094371 ,  0.73244566]]))
