In [1]:
import warnings
import os
warnings.filterwarnings("ignore")
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [2]:
import tensorflow as tf
import numpy as np
X = [[2.0, 4.0],[6.0, 8.0]]
Y = np.array([[2.0, 4.0],[6.0, 6.0]], dtype=np.float32)
Z = tf.constant([[2.0, 4.0],[6.0, 8.0]])

In [3]:
print(type(X))
print(type(Y))
print(type(Z))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [4]:
t1 = tf.convert_to_tensor(X, dtype=tf.float32)
t2 = tf.convert_to_tensor(Z, dtype=tf.float32)
t3 = tf.convert_to_tensor(Z, dtype=tf.float32)

In [5]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


Rank

In [6]:
scalar = tf.constant(100)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


Shape

In [7]:
scalar.get_shape()

TensorShape([])

In [8]:
vector.get_shape()

TensorShape([Dimension(5)])

In [9]:
matrix.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [10]:
cube_matrix.get_shape()

TensorShape([Dimension(3), Dimension(3), Dimension(1)])

Data type

In [11]:
tensor_1d = np.array([1,2,3,4,5,6,7,8,9,10])
tensor_1d = tf.constant(tensor_1d)
with tf.Session() as sess:
    print (tensor_1d.get_shape())
    print (sess.run(tensor_1d))
sess.close()

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
tensor_2d = np.array([(1,2,3),(4,5,6),(7,8,9)])
tensor_2d = tf.Variable(tensor_2d)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (tensor_2d.get_shape())
    print (sess.run(tensor_2d))
sess.close()

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
interactive_session = tf.InteractiveSession()
tensor = np.array([1,2,3,4,5])
tensor = tf.constant(tensor)
print(tensor.eval())
interactive_session.close()

[1 2 3 4 5]


In [14]:
tensor_3d = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],[[9, 10, 11], [12, 13, 14], [15, 16, 17]],
                      [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)
with tf.Session() as sess:
    print(tensor_3d.get_shape())
    print(sess.run(tensor_3d))
sess.close()

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


Variables

In [15]:
value = tf.Variable(0, name="value")

In [16]:
one = tf.constant(1)
new_value = tf.add(value, one)
update_value = tf.assign(value, new_value)
initialize_var = tf.global_variables_initializer()

In [17]:
with tf.Session() as sess:
    sess.run(initialize_var)
    print(sess.run(value))
    for _ in range(5):
        sess.run(update_value)
        print(sess.run(value))
sess.close()

0
1
2
3
4
5


Fetches

In [18]:
constant_A = tf.constant([100.0])
constant_B = tf.constant([300.0])
constant_C = tf.constant([3.0])
sum_ = tf.add(constant_A,constant_B)
mul_ = tf.multiply(constant_A,constant_C)
with tf.Session() as sess:
    result = sess.run([sum_,mul_])
    print(result)
sess.close()

[array([400.], dtype=float32), array([300.], dtype=float32)]


Feeds and placeholders

In [19]:
a = 3
b = 2
x = tf.placeholder(tf.float32,shape=(a,b))
y = tf.add(x,x)
data = np.random.rand(a,b)
sess = tf.Session()
print (sess.run(y,feed_dict={x:data}))
sess.close()

[[1.5884585  1.7116479 ]
 [0.37528476 1.574921  ]
 [1.6967345  0.97937965]]
